coordinape/discord-bot

package-lock.json, package.json, src/app/commands/CO.ts, src/app/service/constants/constants.ts, src/app/service/constants/discordServerIds.ts, src/app/utils/Sentry.ts
This PR includes a set of changes to the underlying template, as well as the addition of the main Coordinape command file.
=> coordinape features initial setup part one of many, probably

src/app/api/getDiscordRolesCirclesAlerts.ts, src/app/api/insertDiscordRolesCircles.ts, src/app/api/updateDiscordRolesCirclesAlerts.ts, src/app/api/zeus/const.ts, src/app/api/zeus/index.ts, src/app/commands/test.ts, src/app/interactions/componentInteractions/handlers/configuration/1.1_handleCreateNewEntities.ts, src/app/interactions/componentInteractions/handlers/configuration/2.2_handleRequestApiKeys.ts, src/app/interactions/componentInteractions/handlers/configuration/3.3_handleConfirmAlertsToSend.ts
Store the alerts the user selects
Follow up on https://github.com/coordinape/coordinape/pull/1952#pullrequestreview-1301876711
=> feat: Store alerts

src/app/api/findApiKey.ts, src/app/interactions/componentInteractions/handlers/changeRole/assignRoleHandler.ts
Find the api key before `createUsersMutation`
=> feat: Get user api key

src/app/service/components/getConfigureComponents.ts
=> fix: Defer the config button reply

src/app/app.ts, src/app/interactions/componentInteractions/handlers/changeRole/assignRoleHandler.ts, src/app/interactions/componentInteractions/handlers/configuration/1.1_handleCreateNewEntities.ts, src/app/interactions/componentInteractions/handlers/configuration/2.2_handleRequestApiKeys.ts, src/app/interactions/componentInteractions/handlers/configuration/2_handleLinkCircles.ts, src/app/interactions/componentInteractions/handlers/configuration/3.2_handleAlertsToSend.ts, src/app/interactions/componentInteractions/handlers/configuration/3.3_handleConfirmAlertsToSend.ts, src/app/interactions/componentInteractions/handlers/configuration/handleLinkedCircleAlertsUpdate.ts
Fine grain defers, as when we handle a select we don't reply to the message
=> fix: Fine grain defers

src/app/app.ts, src/app/interactions/componentInteractions/handlers/configuration/2.2_handleRequestApiKeys.ts
The subscription was attached to the parent message, we want it to be attached to the last interaction message
=> refactor: Move subscription to response handler

src/app/interactions/componentInteractions/handlers/configuration/1.1_handleCreateNewEntities.ts
We were showing the final message even when no new entities were created
Only show the final message if at least one new entity is created
=> fix: Only show the final message on success

src/app/interactions/componentInteractions/handlers/configuration/2.2_handleRequestApiKeys.ts
Adding some logs here as I'm unable to reproduce this locally
=> debug: Add logs to handleRequestApiKeys

src/app/app.ts, src/app/interactions/componentInteractions/handlers/configuration/1.1_handleCreateNewEntities.ts, src/app/interactions/componentInteractions/handlers/configuration/2.3_handleSkipLinkCircleButton.ts, src/app/interactions/componentInteractions/handlers/configuration/index.ts, src/app/interactions/customId.ts
Implement the flow when the user decides not to link a circle
=> feat: Implement skip link circle flow

src/app/server/handlers/nomination.ts
Add logs to the nomination handler to understand why the request is not going throug
=> feat: Add logs to the nomination handler

src/app/server/handlers/nomination.ts
Previous logs https://github.com/coordinape/discord-bot/pull/79 were not effective, adding a few more
=> feat: Use safeParse and add a few logs

.env.example, src/app/server/handlers/middleware/auth.ts, src/app/server/handlers/middleware/index.ts, src/app/server/index.ts
Add authorization middleware so that the discord bot can reject unauthorized requests
=> feat: Request authorization

src/app/api/createUsersMutation.ts, src/app/api/zeus/const.ts, src/app/api/zeus/index.ts, src/app/interactions/componentInteractions/handlers/configuration/handleAddUserCircle.ts
`UserResponse` is not a return type from `createUsers`
=> fix: Remove invalid return field

src/app/api/createUsersMutation.ts, src/app/interactions/componentInteractions/handlers/configuration/handleAddUserCircle.ts
`entrance` was missing, manual for now... should add discord bot later
=> fix: Add missing entrance

src/app/api/deleteUsersMutation.ts, src/app/interactions/componentInteractions/handlers/configuration/handleRemoveUserCircle.ts
Implement the delete user flow
=> feat: Delete user

src/app/server/handlers/userAdded.ts, src/app/server/handlers/userOptsOut.ts, src/app/server/handlers/userRemoved.ts, src/app/server/utils/getUsername.ts
Add the profile name if we have it in the discord message
Complements https://github.com/coordinape/coordinape/pull/1977
https://github.com/coordinape/discord-bot/issues/86
=> feat: Add profile name in the message

src/app/server/handlers/end.ts, src/app/server/handlers/start.ts
The `circleId` comes as a number, bot was expecting a `string`
=> fix: Epoch start and end bug

src/app/api/getDiscordRolesCirclesAlerts.ts
=> fix: getDiscordRolesCirclesAlerts

README.md
TODO: Kpie please document the manual changes you're making to the zeus
codegen in the repo.
=> Update the README with a bit more accurate info

src/app/common/interactionComponents.ts, src/app/interactions/handlers/configuration/handleLinkCircles.ts, src/app/interactions/handlers/configuration/handleRequestApiKeys.ts, src/app/server/handlers/nomination.ts, src/app/service/constants/roleIds.ts
Update codebase with the production endpoint for coordinape
=> refactor: Production endpoints

src/app/interactions/handlers/configuration/handleCreateNewEntities.ts
Create a private channel for the circle flow
=> feat: Create a private channel for the circle flow

src/app/commands/coordinape.ts
Only server admin can configure the bot
=> feat: Add admin permissions back

package.json, yarn.lock
Add `tsconfig-paths` as a dependency
=> refactor: Add tsconfig-paths as a dependency

package.json, src/app/app.ts, src/app/events/RateLimit.ts, src/app/utils/Log.ts, yarn.lock
=> refactor: Remove logger dna

src/app/app.ts, src/app/commands/coordinape.ts, src/app/commands/test.ts, src/app/interactions/customId.ts, src/app/interactions/handlers/contribution/handleContribution.ts, src/app/interactions/handlers/contribution/index.ts, src/app/interactions/handlers/index.ts
Contribution flow UX only.
TODO in a another PR:
* Check that the user is has their account linked
* Check this message was sent from a channel linked to a circle that the user belongs
=> feat: Implement contribution UX

src/app/interactions/handlers/configuration/handleAlertsToSend.ts, src/app/server/handlers/dailyUpdate.ts, src/app/server/index.ts
Notify users on a daily basis about the epoch
Add a daily update handler and endpoint
Trigger on the coordinape app; https://github.com/coordinape/coordinape/pull/2042
Updated the `dailyUpdate` cron to run every minute and saw the message being sent correctly
=> feat: Add daily update handler

src/app/server/utils/getUsername.ts
=> fix: Remove unnecessary curly brace

package.json, src/app/api/findUserId.ts, src/app/api/getCircle.ts, src/app/api/gqlClients.ts, src/app/api/insertContributionsOne.ts, src/app/interactions/handlers/contribution/handleContribution.ts, yarn.lock
Implements the subcommand to add contributions
~~Requires https://github.com/coordinape/coordinape/pull/2077~~
=> feat: Add contribution

src/app/api/findUserId.ts, src/app/interactions/handlers/contribution/handleContribution.ts
Fetch the user id using the user's api key
=> fix: Fetch user id with api key

src/app/interactions/handlers/configuration/handleAlertsToSend.ts
Change the alert order, https://www.notion.so/Phase-2-QA-c221864aa5f44cdc9587d540f19e635a?pvs=4#26ddb0abacf84cd49bcfae5be795a9e9
=> refactor: Change alert order

src/app/interactions/handlers/configuration/handleAlertsToSend.ts, src/app/interactions/handlers/configuration/handleLinkedCircleAlertsUpdate.ts
Just a text change for the alerts
=> refactor: Change alerts message

README.md
Remove the last reference to LogDNA from the codebase
=> chore: Remove LogDNA ref from README
